name: Release packages/slice-store

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - packages/slice-store/**

jobs:
  release-PR:
    # only run when PR merged and has changes:packages/slice-store and CI-Release labels
    if: |
      github.event.pull_request.merged == true && 
      contains(github.event.pull_request.labels.*.name, 'changes:packages/slice-store') &&
      !contains(github.event.pull_request.labels.*.name, 'CI-Release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # ref: ${{ github.head_ref || github.ref_name }}

      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build dist
        run: pnpm build

      - name: Create release PR
        run: npm run release-pr:packages/slice-store
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }} 

  release:
    # only run when PR merged and has changes:packages/slice-store and CI-Release labels
    if: |
      github.event.pull_request.merged == true && 
      contains(github.event.pull_request.labels.*.name, 'changes:packages/slice-store') &&
      contains(github.event.pull_request.labels.*.name, 'CI-Release')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # ref: ${{ github.head_ref || github.ref_name }}

      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build dist
        run: pnpm build

      - name: Create tag and publish
        run: npm run release:packages/slice-store
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Debug Git status
        run: |
          git status
          git branch
          git rev-parse --abbrev-ref HEAD